package com.fortytwotalents.optimizer;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.boot.autoconfigure.condition.ConditionEvaluationReport;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class TrainingRunApplicationListenerTest {

	@TempDir
	Path tempDir;

	@Test
	void writeTrainingFile_createsFileWithLoadedConfigurations() throws IOException {
		AutoConfigurationOptimizerProperties properties = new AutoConfigurationOptimizerProperties();
		properties.setOutputDirectory(tempDir.toString());
		properties.setOutputFile("test-training.properties");

		ConditionEvaluationReport report = mock(ConditionEvaluationReport.class);
		TrainingRunApplicationListener listener = new TrainingRunApplicationListener(properties, report);

		List<String> configs = List.of(
				"org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration",
				"org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration");

		listener.writeTrainingFile(configs);

		Path outputFile = tempDir.resolve("test-training.properties");
		assertThat(outputFile).exists();

		String content = Files.readString(outputFile);
		assertThat(content).contains(OptimizedAutoConfigurationEnvironmentPostProcessor.LOADED_CONFIGURATIONS_KEY)
			.contains("org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration")
			.contains("org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration")
			.contains("# Generated by Spring Boot Autoconfiguration Optimizer");
	}

	@Test
	void writeTrainingFile_handlesEmptyConfigurationList() throws IOException {
		AutoConfigurationOptimizerProperties properties = new AutoConfigurationOptimizerProperties();
		properties.setOutputDirectory(tempDir.toString());
		properties.setOutputFile("empty-training.properties");

		ConditionEvaluationReport report = mock(ConditionEvaluationReport.class);
		TrainingRunApplicationListener listener = new TrainingRunApplicationListener(properties, report);

		listener.writeTrainingFile(List.of());

		Path outputFile = tempDir.resolve("empty-training.properties");
		assertThat(outputFile).exists();

		String content = Files.readString(outputFile);
		assertThat(content).contains(OptimizedAutoConfigurationEnvironmentPostProcessor.LOADED_CONFIGURATIONS_KEY);
	}

	@Test
	void loadAvailableAutoConfigurations_loadsFromClasspath() throws IOException {
		AutoConfigurationOptimizerProperties properties = new AutoConfigurationOptimizerProperties();
		ConditionEvaluationReport report = mock(ConditionEvaluationReport.class);
		TrainingRunApplicationListener listener = new TrainingRunApplicationListener(properties, report);

		// Should load Spring Boot's own auto-configurations (which are on test classpath)
		var autoConfigs = listener.loadAvailableAutoConfigurations();
		assertThat(autoConfigs).isNotEmpty();
	}

	@Test
	void detectLoadedAutoConfigurations_returnsMatchedConfigs() throws IOException {
		AutoConfigurationOptimizerProperties properties = new AutoConfigurationOptimizerProperties();
		ConditionEvaluationReport report = mock(ConditionEvaluationReport.class);

		// Set up condition evaluation report with a known auto-configuration
		String knownAutoConfig = "org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration";
		ConditionEvaluationReport.ConditionAndOutcomes outcomes = mock(
				ConditionEvaluationReport.ConditionAndOutcomes.class);
		when(outcomes.isFullMatch()).thenReturn(true);
		when(report.getConditionAndOutcomesBySource()).thenReturn(java.util.Map.of(knownAutoConfig, outcomes));

		TrainingRunApplicationListener listener = new TrainingRunApplicationListener(properties, report);
		List<String> detected = listener.detectLoadedAutoConfigurations();

		// The known auto-configuration should be in the result since it matches and is in
		// the imports file
		assertThat(detected).contains(knownAutoConfig);
	}

}
