package com.fortytwotalents.petclinic;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Properties;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Integration tests verifying the full train and inject cycle for the autoconfiguration
 * optimizer.
 *
 * <p>
 * These tests are executed by Maven Failsafe after:
 * <ol>
 * <li>the {@code inject} goal has run during the {@code prepare-package} phase (embeds
 * the optimizer core into {@code target/classes}), and</li>
 * <li>the {@code train} goal has run during the {@code pre-integration-test} phase
 * (performs the training run and writes the generated properties file).</li>
 * </ol>
 *
 * <p>
 * The path to the generated training file is passed as the {@code trainingFile} system
 * property by the Maven Failsafe plugin configuration.
 */
class PetClinicOptimizerIT {

	static final String LOADED_CONFIGURATIONS_KEY = "autoconfiguration.optimizer.loaded-configurations";

	/**
	 * Verifies that the {@code inject} goal successfully embedded the optimizer core
	 * classes into the build output directory.
	 *
	 * <p>
	 * The {@code OptimizedAutoConfigurationImportFilter} class is not declared as a
	 * project dependency; it is only present if the {@code inject} goal ran and copied
	 * the class into {@code target/classes}.
	 */
	@Test
	void optimizerCoreIsInjectedIntoBuildOutput() {
		// The inject goal writes core classes to ${project.build.outputDirectory}.
		// Verify the filter class file is present — it is NOT a declared dependency
		// so the only way it gets here is via the inject goal.
		Path classFile = Path.of(
				System.getProperty("projectBuildOutputDirectory", "target/classes"),
				"com/fortytwotalents/optimizer/OptimizedAutoConfigurationImportFilter.class");
		assertThat(classFile).as("OptimizedAutoConfigurationImportFilter should be in the build output "
				+ "(injected by the inject goal at prepare-package phase)").exists();
	}

	/**
	 * Verifies that the {@code train} goal generated the optimizer properties file.
	 */
	@Test
	void trainingFileWasGenerated() throws IOException {
		Path trainingFile = resolveTrainingFile();
		assumeTrue(trainingFile != null, "trainingFile system property not configured - skipping");
		assumeTrue(Files.exists(trainingFile), "Training file not found - train goal may not have run");

		assertThat(trainingFile).isReadable();
		assertThat(Files.size(trainingFile)).isGreaterThan(0);
	}

	/**
	 * Verifies that the training file contains the expected
	 * {@code autoconfiguration.optimizer.loaded-configurations} key with at least one
	 * auto-configuration entry.
	 */
	@Test
	void trainingFileContainsLoadedAutoConfigurations() throws IOException {
		Path trainingFile = resolveTrainingFile();
		assumeTrue(trainingFile != null, "trainingFile system property not configured - skipping");
		assumeTrue(Files.exists(trainingFile), "Training file not found - train goal may not have run");

		Properties props = loadProperties(trainingFile);

		String loadedConfigs = props.getProperty(LOADED_CONFIGURATIONS_KEY);
		assertThat(loadedConfigs).as("Training file must contain the '%s' key", LOADED_CONFIGURATIONS_KEY)
			.isNotBlank();

		long configCount = Arrays.stream(loadedConfigs.split(",")).map(String::trim).filter(s -> !s.isBlank()).count();
		assertThat(configCount).as("Training file must list at least one auto-configuration").isGreaterThan(0);
	}

	/**
	 * Verifies that the training file contains the human-readable summary comment block
	 * added by the optimizer.
	 */
	@Test
	void trainingFileContainsSummaryComments() throws IOException {
		Path trainingFile = resolveTrainingFile();
		assumeTrue(trainingFile != null, "trainingFile system property not configured - skipping");
		assumeTrue(Files.exists(trainingFile), "Training file not found - train goal may not have run");

		String content = Files.readString(trainingFile);
		assertThat(content).contains("# Generated by Spring Boot Autoconfiguration Optimizer");
		assertThat(content).contains("# Total available auto-configurations:");
		assertThat(content).contains("# Total auto-configurations loaded:");
		assertThat(content).contains("# Auto-configurations excluded:");
	}

	private Path resolveTrainingFile() {
		String trainingFilePath = System.getProperty("trainingFile");
		if (trainingFilePath == null || trainingFilePath.isBlank()) {
			return null;
		}
		return Path.of(trainingFilePath);
	}

	private Properties loadProperties(Path file) throws IOException {
		Properties props = new Properties();
		try (InputStream is = Files.newInputStream(file)) {
			props.load(is);
		}
		return props;
	}

}
